version: "3.8"

services:
  app:
    container_name: pro-policy-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config/config.yml:/config/config.yml
    environment:
      # Database Configuration
      - POLICY_GENERAL__SQL__WRITE__HOST=host.docker.internal
      - POLICY_GENERAL__SQL__WRITE__USER=postgres
      - POLICY_GENERAL__SQL__WRITE__PASSWORD=123456789
      - POLICY_GENERAL__SQL__WRITE__DATABASE=PolicyPro
      - POLICY_GENERAL__SQL__WRITE__PORT=5432

    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
