# current language
current_lang: "en"

general:
  logger:
    level: "debug"
  router:
    port: 8090

  sql:
    write:
      host: localhost
      port: "5432"
      user: postgres
      password: "123456789"
      database: PolicyPro


# JWT Configuration
JWT_SECRET_KEY: "your-256-bit-secret-key-here"
JWT_REFRESH_SECRET_KEY: "your-256-bit-secret-key-here"
JWT_ALGORITHM: "HS256"
JWT_ACCESS_TOKEN_EXPIRE_MINUTES: 60
JWT_REFRESH_TOKEN_EXPIRE_DAYS: 7

# Application Messages
ApplicationMessages:
  en:
    UserNotFound:
      Key: "USER_NOT_FOUND"
      Message: "User not found"
    DuplicateUser:
      Key: "DUPLICATE_USER"
      Message: "User already exists."
    InvalidCredentials:
      Key: "INVALID_CREDENTIALS"
      Message: "Invalid credentials"
    InvalidToken:
      Key: "INVALID_TOKEN"
      Message: "Invalid token"
    TokenExpired:
      Key: "TOKEN_EXPIRED"
      Message: "Token has expired"
    InternalServerError:
      Key: "INTERNAL_SERVER_ERROR"
      Message: "An internal server error occurred"
